// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVNTFbY0CuDu7wi4_rT7unhX2_XrR2vU',
    appId: '1:1043353958516:web:9e1945e98ea4d7aff03921',
    messagingSenderId: '1043353958516',
    projectId: 'maamfizza-c4565',
    authDomain: 'maamfizza-c4565.firebaseapp.com',
    storageBucket: 'maamfizza-c4565.appspot.com',
    measurementId: 'G-JP2JESG8MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVFXBnjeDFfZazL7Gu4GuC2V0jcBBTLw',
    appId: '1:1043353958516:android:66edd95426bb1cc7f03921',
    messagingSenderId: '1043353958516',
    projectId: 'maamfizza-c4565',
    storageBucket: 'maamfizza-c4565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJC7nZjxRs2soUGLc8cb7KgKnMVOrI7qM',
    appId: '1:1043353958516:ios:31912d992eff363bf03921',
    messagingSenderId: '1043353958516',
    projectId: 'maamfizza-c4565',
    storageBucket: 'maamfizza-c4565.appspot.com',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJC7nZjxRs2soUGLc8cb7KgKnMVOrI7qM',
    appId: '1:1043353958516:ios:ac3143370726bf94f03921',
    messagingSenderId: '1043353958516',
    projectId: 'maamfizza-c4565',
    storageBucket: 'maamfizza-c4565.appspot.com',
    iosBundleId: 'com.example.tms.RunnerTests',
  );
}
